---
datasources: []
# - name: influx
#   type: influxdb
#   addr: localhost
#   database: mydatabase

# - name: elastic
#   type: elasticsearch
#   addr: localhost:9200
#   index: myindex

storage:
  path: /var/lib/loudml

server:
  listen: localhost:8077
