---
datasources:
 - name: influx
   type: influxdb
   addr: "${influx_addr}"
   database: "${influx_database}"

 - name: elastic
   type: elasticsearch
   addr: "${elastic_url}"
   index: "${elastic_index}"

storage:
  path: /var/lib/loudml

server:
  listen: localhost:8077
