---
datasources:
 - name: influx
   type: influxdb
   addr: ${influx}
   database: ${influx_database}

 - name: elastic
   type: elasticsearch
   addr: ${elastic}
   index: ${elastic_index}

storage:
  path: /var/lib/loudml

server:
  listen: localhost:8077
